//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_Add(SB), $0-16

    MOVQ fl+0(FP), DI
    MOVQ result+8(FP), SI

    WORD $0x078b                 // mov    eax, dword [rdi]
    WORD $0x0689                 // mov    dword [rsi], eax
    RET
